### ISSUE TITLE
Change template file extension

### ISSUE THREAD

**Issue by btrem** [paulhtremblay/covid19#20]
It might be easier working on templates if they had a different extension. Perhaps .html.jinja, or jinja.html. Or maybe j2.html. So instead of base.html it would be base.html.jinja or base.j2.html. Thoughts? Preferences?

**Comment by paulhtremblay** [comment]
Sure. We will lose HTML highlighting in a text editor, though. Is there jinja highlighting?

**Comment by btrem** [comment]
My editor does not have jinja syntax highlighting. But I can tell it to use html highlighting for arbitrary extensions, e.g., .jinja. Oftentimes, editors will use html highlighting if it's one part of the extension. Is that the case for you?

**Comment by paulhtremblay** [comment]
I just checked, and VIM has jinja highlighting. What text editor do you use?

**Comment by btrem** [comment]
Coda2, which does not have jinja highlighting, but I can set Coda to use html highlighting for any extension, so nothing lost in terms of that. But something gained in that I can tell what files I'm working on or about to open. So, what extension do you want? What works best for you using VIM?

**Comment by btrem** [comment]
Revisiting this issue. Do you have a preference for an extension for jinja2 templates?

**Comment by paulhtremblay** [comment]
sure, j2 is fine.

**Comment by btrem** [comment]
I introduced a bug with this branch that is already merged. The make files reference .html templates. A bug fix is ready to push.
