### ISSUE TITLE
jquery

### ISSUE THREAD

**Issue by btrem** [paulhtremblay/covid19#22]
We could add some features to the site like putting all contributors in the `<address>` element, or putting in email addresses in a way that makes it somewhat difficult for spammers to harvest them. We'd want a library to do these things. Any thoughts on adding jquery via cdn? If yes, assign it to me and I'll add it to the base.html template.

**Comment by paulhtremblay** [comment]
Hoping to use lots of jquery on the page to make it modern looking and nice. The view for a phone is almost unviewable. Do you want to use a framework like react? Lots of learning but will look good on a resume.

**Comment by btrem** [comment]
That's live site is working with somewhat broken templates. Look at the source code, and you see a `<nav>` element before the `<head>` element. That's bound to cause problems. A conforming browser would probably have to ignore at least parts of the elements inside `<head>` since the `<body>` element is implicitly opened with the opening `<nav>` tag.

Also the `<meta viewport>` element is missing from the `<head>` element. Those are both resolved in branch simplify templates.

**Comment by btrem** [comment]
Also, on the live site, there is no site.css file (it returns not found).
