### ISSUE TITLE
Where to host website

### ISSUE THREAD

**Issue by paulhtremblay** [paulhtremblay/covid19#3]
keeping this simple, we have 2 options:
1. use a bucket  static. (if we do this, I will use AWS and cloudfront to get https) 
-- simple
-- you can view your work on  a local machine
-- pages are static and do not allow for interaction

2. Use a hosting service, or deploy using AWS. (request -> response architecture)
-- would take commitment
-- site can be interactive with graphs

**Comment by btrem** [comment]
If it's shared hosting, that's not too expensive. I'm afraid that's the only experience I can share. I've never done aws. How much is that per month?

**Comment by paulhtremblay** [comment]
Cost is not the issue. It will be relatively cheap whatever direction we go. (I will pay the cost regardless.) Hosting with a full deployment (like AWS) takes more work than just dumping to a bucket. The question is whether other developers want the freedom and responsibility of  creating a full-blown website
