### ISSUE TITLE
Create pulldown for states list page

### ISSUE THREAD

**Issue by paulhtremblay** [paulhtremblay/covid19#34]
https://www.seattle-data.com/states_list.html give a bad user experience. Normally, there would be a pulldown. Jquery could replace the contents of the list with a pulldown, or we could implement the code more direct.

**Comment by btrem** [comment]
What should the main nav links be? Some of the graphs are a little beyond my comprehension, so it's hard to organize the site. My first attempt:

home  countries  states  comparisons

The comparisons folder would hold e.g. Sweden vs. As an alternative, maybe states-deaths should go in the /states/ folder, while Sweden vs. should go in /countries/. That might make more sense, keeping things organized into their own folders.

ISTM that the /states/ and /countries/ pages should have more than a list of links. There are a few things we could do, maybe the Sweden vs. could be part of the content of /countries/, that sort of thing.

**Comment by btrem** [comment]
How do I get a python list of states and territories that will have their own pages? I tried to copy and whittle down by_state.py, but there's too much I don't understand, and I've failed.

**Comment by btrem** [comment]
Never mind. I think I have it figured out. When I push the branch, you can decide if it cuts the mustard.

**Comment by btrem** [comment]
Where do you want javascript/jquery files to go? Where do you want graphic files? Do you want folders under templates?
