### ISSUE TITLE
simplifying urls

### ISSUE THREAD

**Issue by btrem** [paulhtremblay/covid19#35]
I want to simpify urls. But before I do, I'd like Amazon to send text/html content header for files without an extension.

**Comment by paulhtremblay** [comment]
Not sure what you mean.

**Comment by btrem** [comment]
AFAIK, you can configure s3 to send content type headers depending on the file extension. I'm hoping that for files <em>without</em> an extension, you can configure it to send one:
Content-Type: text/html; charset=utf-8

**Comment by paulhtremblay** [comment]
Where is the link on how to do this?

**Comment by btrem** [comment]
From a reply to an email I sent to a listserv I subscribe to (my question first, followed by a reply):

> I'm working on an S3 site, and rewrite is not available. If we create 
> extensionless files, can S3 be configured to send a text/html mime type? 
> So far, I've only found explanations for setting mime types base on the 
> file's extension, and the S3 site is not registered to me, so I can't 
> fiddle around.

I've never hosted a static site on S3, so I don't know for sure whether 
this'll do what you hope, but you can add metadata to objects; find the 
object in the console, right-click, select "Change metadata", and 
add/edit a "Content-Type" key to be "text/html".

**Comment by paulhtremblay** [comment]
I already do this:
https://github.com/paulhtremblay/covid19/blob/master/upload_html_to_bucket_s3.py#L29

**Comment by btrem** [comment]
Ok, sorry, I didn't realize that. Maybe then I can create shorter urls. I'll create a test case. The make_about.py will create about instead of about.html. Then we can see if S3 sends the right header for that resource.

**Comment by paulhtremblay** [comment]
Yea, it will. I have tested this multiple times at work on GCP and on AWS. If the mime type is html, and you click on it, it opens an HTML page. If it is not, it just downloads the file. You can have access to the bucket if you want.
