### ISSUE TITLE
get credentials/set up environment for btrem

### ISSUE THREAD

**Issue by paulhtremblay** [paulhtremblay/covid19#59]
Get Google creds
Get AWS creds

**Comment by paulhtremblay** [comment]
I generated the AWS key for access to S3. Do you have a pgp key?

**Comment by paulhtremblay** [comment]
there is a script
test_creds_s3.py

in master that will let you know if the creds are working.

**Comment by btrem** [comment]
'fraid not:

botocore.exceptions.NoCredentialsError: Unable to locate credentials

**Comment by btrem** [comment]
Am I supposed to get credentials somewhere? Or use my gpg public key in some manner?

**Comment by paulhtremblay** [comment]
Two ways to do this. first try
export AWS_ACCESS_KEY_ID=<key>
export AWS_SECRET_ACCESS_KEY=<key>

then run the script and see if that works
(That is the right way, so will not do the workaround for now)

**Comment by btrem** [comment]
Um, ok, but what goes in the 'xxx' part? What are the keys? If I run it with the string 'xxx' and 'xxxx' I get:
botocore.exceptions.ClientError: An error occurred (InvalidAccessKeyId) when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.

**Comment by paulhtremblay** [comment]
Unencrypt your keys in the file I sent you

**Comment by btrem** [comment]
Oh ffs, I didn't see the attachment.

**Comment by btrem** [comment]
I get no error notifications (nor ouput of any kind) when I run python test_creds _s3.py

**Comment by paulhtremblay** [comment]
Is successful then

**Comment by btrem** [comment]
So now what do I do? If I have a new local branch, do I name it dev? Does that deploy to the test site?

**Comment by paulhtremblay** [comment]
from your branch

bash make.sh -vu
Will upload to the bucket (-v for verbose, -u for upload

**Comment by btrem** [comment]
botocore.exceptions.NoCredentialsError: Unable to locate credentials

Since I've never done this, I probably need a bit more detailed instructions. Where do I put the credentials that you emailed me so that make.sh can find them?

**Comment by paulhtremblay** [comment]
You have to create environmental variables like you did when you ran
test_creds a few days ago. The library can't find those 2 variables.

**Comment by btrem** [comment]
Cool, I got the site to upload to the test bucket. There's a problem with the test site, however. See comment in issue #11.
