### ISSUE TITLE
Fix pull down menus for comparisions

### ISSUE THREAD

**Issue by paulhtremblay** [paulhtremblay/covid19#72]
I created a branch in "masks". The new code creates a new page to compare the change in cases after mask mandates. The page is state-masks. I added the link in comparisons_index.j2 , but can't find the js code to add this to the comparisons menus.

**Comment by btrem** [comment]
Links in the main site navigation are static links generated by make_nav.py and nav.j2. There are 2 levels. The top level are visible on page load. The submenus are hidden on load, and shown via nav-submenu.js when a user clicks an arrow. (The same .js file also handles the search.)

So to resolve this issue I just added the link to nav.j2 in #73. This is an FYI in case you want to add something else to comparisons.

I tested the site, but I'm leaving this issue open in case you want changes.

**Comment by paulhtremblay** [comment]
Thanks. Seems to be working now.
